---
global:
  scrape_interval: "1m"
  scrape_timeout: "10s"
  evaluation_interval: "1m"

alerting:

rule_files:

scrape_configs:
  - job_name: 'go-api'
    static_configs:
      - targets: ['api:8080']
